### ISSUE TITLE
Configurable position relative to screen height

### ISSUE THREAD

**Issue by apoapostolov** [filloax/boss-hp-bars#3]
This would allow to reposition the bar to avoid having other bottom screen mods (Custom Hotbar, and in this case Calendar) to overlap with the Boss HP in a way that cannot be resolved without removing said mods. 

![image](https://user-images.githubusercontent.com/4083812/116000859-98dd9e80-a5fa-11eb-9bf6-a89dbf201a1c.png)

**Comment by filloax** [comment]
Actually you're in luck, I just added the option to move it and scale it. Client side only, though.
